services:
  - type: web
    name: deepface-fastapi
    env: docker
    plan: free
    autoDeploy: true
    branch: master
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000

